# SAFETRAILS cross-platform checksum conformance check.
#
# Re-implements the canonical field string + FNV-1a 16-bit checksum exactly as
# the JS (packet.js), Dart (packet.dart) and C++ (firmware/src/core/packet.cpp)
# codecs do, then asserts it reproduces the reference vectors emitted by Node.
# Run:  python shared/protocol/check_cross_platform.py
# (requires the 'node' binary on PATH to regenerate vectors, else the vectors
#  in the script are asserted on their own)

import subprocess
import sys

MAX_COORD_DECIMALS = 6
NO_VALUE = "-"


def fnv1a16(text: str) -> str:
    h = 0x811C9DC5
    for ch in text:
        h ^= (ord(ch) & 0xFF)
        h = (h * 0x01000193) & 0xFFFFFFFF
    return "%04x" % ((h >> 16) & 0xFFFF)


def normalize_coord(v) -> str:
    s = "" if v is None else str(v).strip()
    if s == "" or s == NO_VALUE:
        return NO_VALUE
    if "." not in s:
        return s
    whole, frac = s.split(".", 1)
    frac = frac[:MAX_COORD_DECIMALS]
    frac = frac.rstrip("0")
    return whole if frac == "" else whole + "." + frac


def canonical(p: dict) -> str:
    path = NO_VALUE if not p.get("path") else ",".join(p["path"])
    lat, lon = normalize_coord(p.get("lat")), normalize_coord(p.get("lon"))
    return "|".join([
        "ST", str(1), str(p.get("type", "")), str(p.get("prio", 0)),
        str(p.get("mid", "")), str(p.get("src", "")), str(p.get("dst", "*")),
        lat, lon, str(p.get("ts", 0)), str(p.get("hop", 0)),
        str(p.get("ttl", 0)), str(p.get("flags", 0)), path,
    ])


def body_sanitized(body: str, max_len: int) -> str:
    out = body.replace("|", ";").replace("\n", "").replace("\r", "")
    return out[:max_len]


def compact(p: dict) -> str:
    frame = canonical(p)
    ck = fnv1a16(frame)
    return f"{frame}|{ck}|{body_sanitized(p.get('body', ''), 120)}"


# Reference vectors generated by shared/protocol/packet.js (see README).
VECTORS = [
    # canonical fields dict, expected compact frame
    (dict(type="SOS", prio=3, mid="SOS-8F23A91", src="T102", dst="RCUE",
          lat="27.9881", lon="86.925", ts=1770000000, hop=0, ttl=8, flags=3,
          path=["RCUE"], body="I need emergency assistance"),
     "ST|1|SOS|3|SOS-8F23A91|T102|RCUE|27.9881|86.925|1770000000|0|8|3|RCUE|"
     "eab3|I need emergency assistance"),
    (dict(type="ACK", prio=3, mid="ACK-SOS-8F23A91", src="RCUE", dst="T102",
          ts=1770000100, hop=0, ttl=9, flags=0, path=[], body="SOS-8F23A91"),
     "ST|1|ACK|3|ACK-SOS-8F23A91|RCUE|T102|-|-|1770000100|0|9|0|-|d1e4|"
     "SOS-8F23A91"),
    (dict(type="BROAD", prio=3, mid="BRD-0001", src="RCUE", dst="*",
          ts=1770000200, hop=0, ttl=12, flags=8, path=[],
          body="FLASH FLOOD WARNING^Avoid Trail Sector B^Safe zone: Trail U"),
     "ST|1|BROAD|3|BRD-0001|RCUE|*|-|-|1770000200|0|12|8|-|cc05|"
     "FLASH FLOOD WARNING^Avoid Trail Sector B^Safe zone: Trail U"),
]


def regen_with_node() -> list:
    """Optionally regenerate vectors with the actual JS codec."""
    script = r"""
const p = require('./packet.js');
const rows = [
  {type:'SOS',prio:3,mid:'SOS-8F23A91',src:'T102',dst:'RCUE',lat:'27.9881',lon:'86.925',
   ts:1770000000,hop:0,ttl:8,flags:3,path:['RCUE'],body:'I need emergency assistance'},
  {type:'ACK',prio:3,mid:'ACK-SOS-8F23A91',src:'RCUE',dst:'T102',ts:1770000100,ttl:9,
   body:'SOS-8F23A91'},
  {type:'BROAD',prio:3,mid:'BRD-0001',src:'RCUE',dst:'*',ts:1770000200,ttl:12,flags:8,
   body:'FLASH FLOOD WARNING^Avoid Trail Sector B^Safe zone: Trail U'},
];
for (const r of rows) console.log(p.toCompact(p.buildPacket(r)));
"""
    try:
        out = subprocess.run(
            ["node", "-e", script], capture_output=True, text=True, check=True,
            cwd="shared/protocol")
        return [ln for ln in out.stdout.splitlines() if ln.startswith("ST|")]
    except (FileNotFoundError, subprocess.CalledProcessError):
        return []


def main() -> int:
    failed = 0
    vectors = VECTORS
    node_frames = regen_with_node()
    if node_frames:
        assert len(node_frames) == len(VECTORS), "vector count mismatch"
        vectors = [(p, f) for (p, _), f in zip(VECTORS, node_frames)]

    for pkt, expected in vectors:
        got = compact(pkt)
        ok = got == expected
        print(("[PASS] " if ok else "[FAIL] ") + got)
        if not ok:
            print("  expected: " + expected)
            print("  ck:       " + fnv1a16(canonical(pkt)))
            failed += 1

    # extra invariants all three codecs share
    assert fnv1a16("ST|1|SOS|3|SOS-8F23A91|T102|RCUE|27.9881|86.925|1770000000|0|8|3|RCUE") == "eab3"
    assert normalize_coord("27.988100") == "27.9881"
    assert normalize_coord("86.925000") == "86.925"
    assert normalize_coord("27.000000") == "27"

    if failed:
        print(f"{failed} vector(s) mismatched")
        return 1
    print("OK: canonical + checksum conform across JS/Dart/C++ conventions")
    return 0


if __name__ == "__main__":
    sys.exit(main())