#include <Arduino.h>
#include <unity.h>

#include "core/packet.h"

using namespace st;

static void test_sosCompactMatchesJsShouldBeByteIdentical() {
  // Vector generated by shared/protocol/packet.js (Node) — cross-platform
  // canonical/checksum equivalence proof for the identical logical packet.
  Packet p;
  p.type = "SOS";
  p.prio = 3;
  p.mid = "SOS-8F23A91";
  p.src = "T102";
  p.dst = "RCUE";
  p.lat = "27.9881";
  p.lon = "86.925";
  p.ts = 1770000000;
  p.hop = 0;
  p.ttl = 8;
  p.flags = 3;
  p.path = {"RCUE"};
  p.body = "I need emergency assistance";

  const std::string expected =
      "ST|1|SOS|3|SOS-8F23A91|T102|RCUE|27.9881|86.925|1770000000|0|8|3|RCUE|eab3|"
      "I need emergency assistance";
  TEST_ASSERT_EQUAL_STRING(expected.c_str(), toCompact(p).c_str());
}

static void test_ackParsesAndReencodes() {
  const std::string frame =
      "ST|1|ACK|3|ACK-SOS-8F23A91|RCUE|T102|-|-|1770000100|0|9|0|-|d1e4|SOS-8F23A91";
  Packet p = parseCompact(frame);
  TEST_ASSERT_TRUE(p.valid);
  TEST_ASSERT_EQUAL_STRING("ACK", p.type.c_str());
  TEST_ASSERT_EQUAL_STRING("RCUE", p.src.c_str());
  TEST_ASSERT_EQUAL_STRING("T102", p.dst.c_str());
  TEST_ASSERT_EQUAL_STRING("-", p.lat.c_str());
  TEST_ASSERT_EQUAL_STRING("SOS-8F23A91", p.body.c_str());
  TEST_ASSERT_EQUAL_STRING(frame.c_str(), toCompact(p).c_str());
}

static void test_broadcastCompact() {
  const std::string frame =
      "ST|1|BROAD|3|BRD-0001|RCUE|*|-|-|1770000200|0|12|8|-|cc05|"
      "FLASH FLOOD WARNING^Avoid Trail Sector B^Safe zone: Trail U";
  Packet p = parseCompact(frame);
  TEST_ASSERT_TRUE(p.valid);
  TEST_ASSERT_TRUE(p.isBroadcast());
  TEST_ASSERT_EQUAL_STRING("FLASH FLOOD WARNING^Avoid Trail Sector B^Safe zone: Trail U",
                           p.body.c_str());
}

static void test_parseJsonFromPhoneChecksumOk() {
  const char* json =
      "{\"v\":1,\"type\":\"SOS\",\"prio\":0,\"mid\":\"SOS-8F23A91\",\"src\":\"T102\","
      "\"dst\":\"RCUE\",\"lat\":\"27.9881\",\"lon\":\"86.925\",\"ts\":1770000000,"
      "\"hop\":0,\"ttl\":8,\"flags\":3,\"path\":[\"RCUE\"],\"ck\":\"4e17\","
      "\"body\":\"I need emergency assistance\"}";
  Packet p = parseJson(json);
  TEST_ASSERT_TRUE(p.valid);
  TEST_ASSERT_EQUAL_STRING("SOS-8F23A91", p.mid.c_str());
  TEST_ASSERT_EQUAL_STRING("27.9881", p.lat.c_str());
  TEST_ASSERT_TRUE(p.ackRequired());
}

static void test_tamperedCompactRejected() {
  std::string bad = "ST|1|SOS|3|SOS-8F23A91|T102|RCUE|27.9881|86.925|1770000000|0|8|3|RCUE|eab3|X";
  bad[19] = 'Z';  // corrupt the mid
  Packet p = parseCompact(bad);
  TEST_ASSERT_FALSE(p.valid);
}

static void test_shortAndJunkFramesRejected() {
  TEST_ASSERT_FALSE(parseCompact("junk").valid);
  TEST_ASSERT_FALSE(parseCompact("ST|1|SOS|too-short").valid);
  TEST_ASSERT_FALSE(parseCompact("ST|2|SOS|3|A|B|C|1|2|3|0|8|3|D|-|x").valid);  // bad version
}

static void test_normalizeCoordConsistent() {
  TEST_ASSERT_EQUAL_STRING("27.9881", normalizeCoord("27.988100").c_str());
  TEST_ASSERT_EQUAL_STRING("86.925", normalizeCoord("86.925000").c_str());
  TEST_ASSERT_EQUAL_STRING("27", normalizeCoord("27.000000").c_str());
  TEST_ASSERT_EQUAL_STRING("-", normalizeCoord("").c_str());
  TEST_ASSERT_EQUAL_STRING("-", normalizeCoord("-").c_str());
}

static void test_midKeepsDash() {
  TEST_ASSERT_EQUAL_STRING("SOS-8F23A91", sanitizeToken("SOS-8F23A91", 16,
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-").c_str());
}

void setup() {
  UNITY_BEGIN();
  RUN_TEST(test_sosCompactMatchesJsShouldBeByteIdentical);
  RUN_TEST(test_ackParsesAndReencodes);
  RUN_TEST(test_broadcastCompact);
  RUN_TEST(test_parseJsonFromPhoneChecksumOk);
  RUN_TEST(test_tamperedCompactRejected);
  RUN_TEST(test_shortAndJunkFramesRejected);
  RUN_TEST(test_normalizeCoordConsistent);
  RUN_TEST(test_midKeepsDash);
  UNITY_END();
}

void loop() { delay(100); }